# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/star-university-q3-2021-group-1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run format
      - run: npm run lint

    # steps:
    #   - checkout
    #   - restore_cache:
    #       keys:
    #         - v1-dependencies-{{ checksum "package.json" }}
    #         - v1-dependencies-

    #   - run: npm install

    #   - save_cache:
    #       paths:
    #         - node_modules
    #       key: v1-dependencies-{{ checksum "package.json" }}

    #   - run: npm run test
    #   - run: npm run format
    #   - run: npm run lint

  # deploy:
  #   docker:
  #     - image: circleci/node:12

  #     steps:
  #       - checkout
      # - run: npm run build
      # - run: npm run deploy
      
